version: "3.8"

services:
  kms:
    image: nsmithuk/local-kms
    volumes:
      - ./kms-data:/data
      - ./kms-init:/init
    ports:
      - 4699:8080

  rly-sol0:
    image: centralized-relay:latest
    volumes:
      - ./rly-sol0-data:/home/relayer/.centralized-relay
      - ./.aws:/home/relayer/.aws
      - ./wallets:/home/relayer/wallets
    environment:
      - AWS_ENDPOINT_URL=http://kms:8080
    depends_on:
      - kms
    entrypoint: /home/relayer/.centralized-relay/entrypoint.sh

  rly-sol1:
    image: centralized-relay:latest
    volumes:
      - ./rly-sol1-data:/home/relayer/.centralized-relay
      - ./.aws:/home/relayer/.aws
      - ./wallets:/home/relayer/wallets
    environment:
      - AWS_ENDPOINT_URL=http://kms:8080
    depends_on:
      - kms
    entrypoint: /home/relayer/.centralized-relay/entrypoint.sh

  rly-sui0:
    image: centralized-relay:latest
    volumes:
      - ./rly-sui0-data:/home/relayer/.centralized-relay
      - ./.aws:/home/relayer/.aws
      - ./wallets:/home/relayer/wallets
    environment:
      - AWS_ENDPOINT_URL=http://kms:8080
    depends_on:
      - kms
    entrypoint: /home/relayer/.centralized-relay/entrypoint.sh

  rly-sui1:
    image: centralized-relay:latest
    volumes:
      - ./rly-sui1-data:/home/relayer/.centralized-relay
      - ./.aws:/home/relayer/.aws
      - ./wallets:/home/relayer/wallets
    environment:
      - AWS_ENDPOINT_URL=http://kms:8080
    depends_on:
      - kms
    entrypoint: /home/relayer/.centralized-relay/entrypoint.sh

  rly-stellar0:
    image: centralized-relay:latest
    volumes:
      - ./rly-stellar0-data:/home/relayer/.centralized-relay
      - ./.aws:/home/relayer/.aws
      - ./wallets:/home/relayer/wallets
    environment:
      - AWS_ENDPOINT_URL=http://kms:8080
    depends_on:
      - kms
    entrypoint: /home/relayer/.centralized-relay/entrypoint.sh

  rly-stellar1:
    image: centralized-relay:latest
    volumes:
      - ./rly-stellar1-data:/home/relayer/.centralized-relay
      - ./.aws:/home/relayer/.aws
      - ./wallets:/home/relayer/wallets
    environment:
      - AWS_ENDPOINT_URL=http://kms:8080
    depends_on:
      - kms
    entrypoint: /home/relayer/.centralized-relay/entrypoint.sh