version: "3.8"

services:
  kms:
    image: nsmithuk/local-kms
    volumes:
      - ./kms-data:/data
      - ./kms-init:/init
    ports:
      - 4699:8080

  rly-leader:
    image: centralized-relay:cluster
    volumes:
      - ./rly-leader-data:/home/relayer/.centralized-relay
      - ./rly-cluster-keys/leader:/home/relayer/.centralized-relay/keystore/cluster
      - ./.aws:/home/relayer/.aws
      - ./wallets:/home/relayer/wallets

    environment:
      - AWS_ENDPOINT_URL=http://kms:8080
    depends_on:
      - kms
    entrypoint: /home/relayer/.centralized-relay/entrypoint.sh

  rly-follower0:
    image: centralized-relay:cluster
    volumes:
      - ./rly-follower0-data:/home/relayer/.centralized-relay
      - ./rly-cluster-keys/follower0:/home/relayer/.centralized-relay/keystore/cluster
      - ./.aws:/home/relayer/.aws
      - ./wallets:/home/relayer/wallets
    environment:
      - AWS_ENDPOINT_URL=http://kms:8080
    depends_on:
      - kms
    entrypoint: /home/relayer/.centralized-relay/entrypoint.sh

  rly-follower1:
    image: centralized-relay:cluster
    volumes:
      - ./rly-follower1-data:/home/relayer/.centralized-relay
      - ./rly-cluster-keys/follower1:/home/relayer/.centralized-relay/keystore/cluster
      - ./.aws:/home/relayer/.aws
      - ./wallets:/home/relayer/wallets
    environment:
      - AWS_ENDPOINT_URL=http://kms:8080
    depends_on:
      - kms
    entrypoint: /home/relayer/.centralized-relay/entrypoint.sh