global:
  timeout: 10s
  kms-key-id: 5ef77041-d1e6-4af1-9a41-e49a4b45efb6
  cluster-mode:
    enabled: true
    key: 04df721ea061345f51f7d60b71a93704ba96a167c7a77b28c18a2a9fe00859a40fdd60fb33a9141c9d72abace133461080dea230405c422a1ef24056e3eeb86f6d
chains:
  archway:
    type: cosmos
    value:
      rpc-url: https://rpc.constantine.archway.io:443
      start-height: 0
      address: ""
      contracts:
        connection: archway1dq3g9k26dcnzxyp236t0nan7nt9jp82hzdjc43naxchkuz6g9z6s8x33f4
      finality-block: 0
      nid: archway
      decimals: 18
      disabled: true
      cluster-mode: true
      grpc-url: grpc.constantine.archway.io:443
      keyring-backend: memory
      keyring-dir: /Users/sherpalden/.centralized-relay/archway
      account-prefix: archway
      denomination: aconst
      gas-prices: 900000000000aconst
      gas-adjustment: 1.5
      min-gas-amount: 20000
      max-gas-amount: 4000000
      tx-confirmation-interval: 5s
      broadcast-mode: sync
      sign-mode: SIGN_MODE_DIRECT
      simulate: true
      extra-codecs: ""
      block-batch-size: 50
  avalanche:
    type: evm
    value:
      rpc-url: https://api.avax-test.network/ext/bc/C/rpc
      start-height: 0
      address: ""
      contracts:
        connection: 0x0789F14b511292DE6A5b63304f41854e4d188Bd6
      finality-block: 10
      nid: 0xa869.fuji
      decimals: 18
      disabled: true
      cluster-mode: true
      websocket-url: wss://ws-nd-507-756-317.p2pify.com/b01d81c64a3b7454f7a40a20ef44a1ce/ext/bc/C/ws
      gas-min: 0
      gas-limit: 100056000
      gas-adjustment: 50
      block-batch-size: 50
  icon:
    type: icon
    value:
      rpc-url: https://lisbon.net.solidwallet.io/api/v3/
      start-height: 0
      address: hxaca3b8ce6df4f9480e787e8ab95314fc155b3e72
      contracts:
        aggregation: cx89b8b5c95c4ff38e83ed15374caf854dca0c51d4
      finality-block: 0
      nid: 0x2.icon
      decimals: 18
      disabled: false
      cluster-mode: true
      step-min: 1
      step-limit: 100000000000
      step-adjustment: 50
  stellar:
    type: stellar
    value:
      commonconfig:
        rpc-url: ""
        start-height: 0
        address: ""
        contracts: {}
        finality-block: 0
        nid: ""
        decimals: 0
        disabled: false
        cluster-mode: true
      chain-id: ""
      horizon-url: https://rpc.ankr.com/premium-http/stellar_testnet_horizon/98af665db4f1c6be2ed8ce7d8caed10aade053c5bd7880844d8806b0eada8317
      soroban-url: https://rpc.ankr.com/stellar_testnet_soroban/98af665db4f1c6be2ed8ce7d8caed10aade053c5bd7880844d8806b0eada8317
      address: ""
      contracts:
        connection: CABCT3EBRZDTCBY5W2CHAMLF4GWU6RJSAV2QIV6LFTLQU7RLWX7T6VWN
      nid: stellar-test
      home-dir: /home/relayer/.centralized-relay
      max-inclusion-fee: 100000
      network-passphrase: Test SDF Network ; September 2015
      start-height: 0
      disabled: true
      poll-interval: 0s

  solana:
    type: solana
    value:
      disabled: true
      rpc-url: https://rpc.ankr.com/solana_devnet
      address:
      xcall-program: BknkMw3sonNXVTW2mzuhKEJmmt4PSVei1HbQiDuWVny4
      connection-program: DR7DDmazQVpJSGxLSiAQZcwQD9HpB2yHghBmn5Skad4C
      other-connections:
      cp-nids:
        - 0x2.icon
      alt-address:
      nid: solana-test
      home-dir: /home/relayer/.centralized-relay
      start-tx-sign:
      tx-confirmation-time: 1s

  sui:
    type: sui
    value:
      rpc-url: https://rpc.ankr.com/sui_testnet
      address:
      nid: sui-test
      xcall-package-id: 0xff60814fac7930b9890fc6582efa0e02e72956584d18adef77d23ed4643325bd
      xcall-storage-id: 0x60add4475c91742470074396ba29b6d62572abd1ac08c18abe228be949c21420
      connection-module: cluster_entry
      connection-id: cluster-1
      connection-cap-id: 0x68f3d6261631c7a83159d84017dbf3a984b0e137853f0f5cb62e101ebb042ca3
      gas-limit: 5000000
      disabled: true
      start-tx-digest:
      poll-interval: 6s
