global:
  timeout: 10s
  kms-key-id: 5ef77041-d1e6-4af1-9a41-e49a4b45efb6
  cluster-mode:
    enabled: true
    key: 0483e46ba078c57214cb804c23caa2236d4d8865cd3a5108ad415965fc5adab04dcd99211aa91c9cd5dcdd03b74ffb4db5c63b2a35e479e6c6b997c41625c19d34
chains:
  avalanche:
    type: evm
    value:
      rpc-url: https://api.avax-test.network/ext/bc/C/rpc
      start-height: 0
      address: 0x2e73d181EC82796E9CEB77950e9488441ABaFa04
      contracts:
        connection: 0x0789F14b511292DE6A5b63304f41854e4d188Bd6
        xcall: 0x28ecb198e86a7FcA1cf51032635967fc26cDDAaD
      finality-block: 10
      nid: 0xa869.fuji
      decimals: 18
      disabled: false
      cluster-mode: true
      websocket-url: wss://ws-nd-507-756-317.p2pify.com/b01d81c64a3b7454f7a40a20ef44a1ce/ext/bc/C/ws
      gas-min: 0
      gas-limit: 100056000
      gas-adjustment: 50
      block-batch-size: 50
  icon:
    type: icon
    value:
      rpc-url: https://lisbon.net.solidwallet.io/api/v3/
      start-height: 0
      address: hx71d3f2e4d7973bd6b8e818fa0174f81b064d6548
      contracts:
        aggregation: cx89b8b5c95c4ff38e83ed15374caf854dca0c51d4
        connection: cxdccc9298c4cfd0b505c50b6ec1bc111bd442d080
        xcall: cx15a339fa60bd86225050b22ea8cd4a9d7cd8bb83
      finality-block: 0
      nid: 0x2.icon
      decimals: 18
      disabled: false
      cluster-mode: true
      step-min: 1
      step-limit: 100000000000
      step-adjustment: 50
  stellar:
    type: stellar
    value:
      disabled: false
      nid: stellar-test
      soroban-url: https://rpc.ankr.com/stellar_testnet_soroban/98af665db4f1c6be2ed8ce7d8caed10aade053c5bd7880844d8806b0eada8317
      horizon-url: https://rpc.ankr.com/premium-http/stellar_testnet_horizon/98af665db4f1c6be2ed8ce7d8caed10aade053c5bd7880844d8806b0eada8317
      address: GCBQGYS4ZB4TJBXLECEKDY33RZ7ERQZ4DXWTWVRHLQSKPJ67IEQYMBOD
      contracts:
        connection: CABCT3EBRZDTCBY5W2CHAMLF4GWU6RJSAV2QIV6LFTLQU7RLWX7T6VWN
        xcall: CABHZ2LMZTQSI66YXBJK2FAFQTIRG44ROFGIHGZJR7VJR3J7B5OX2F5E
      max-inclusion-fee: 100000
      block-interval: 5s
      network-passphrase: Test SDF Network ; September 2015
      start-height: 0
  archway:
    type: cosmos
    value:
      rpc-url: https://rpc.constantine.archway.io:443
      start-height: 0
      address: archway1fmfsejk7d6xeg5n63c5ljwaup02tv54c55263h
      contracts:
        connection: archway1dq3g9k26dcnzxyp236t0nan7nt9jp82hzdjc43naxchkuz6g9z6s8x33f4
        xcall: archway1h04c8eqr99dnsw6wqx80juj2vtuxth70eh65cf6pnj4zan6ms4jqshc5wk
      finality-block: 0
      nid: archway
      decimals: 18
      disabled: false
      grpc-url: grpc.constantine.archway.io:443
      keyring-backend: memory
      keyring-dir: /Users/sherpalden/.centralized-relay/archway
      account-prefix: archway
      denomination: aconst
      gas-prices: 900000000000aconst
      gas-adjustment: 1.5
      min-gas-amount: 20000
      max-gas-amount: 4000000
      tx-confirmation-interval: 5s
      broadcast-mode: sync
      sign-mode: SIGN_MODE_DIRECT
      simulate: true
      extra-codecs: ""
      block-batch-size: 50

  solana:
    type: solana
    value:
      disabled: false
      rpc-url: https://rpc.ankr.com/solana_devnet
      address: 7qx1U39XneecHWMPPY172rtTcEBDRH7t9Cb4TNTwkAZm
      xcall-program: BknkMw3sonNXVTW2mzuhKEJmmt4PSVei1HbQiDuWVny4
      connection-program: DR7DDmazQVpJSGxLSiAQZcwQD9HpB2yHghBmn5Skad4C
      other-connections:
      dapps:
        - name: xcall_manager
          program-id: 4eAQxDi6UJokDysb9YMrXNJNcRChotpYory5M5ReD16i
          config-prefix: state
        - name: balanced_dollar
          program-id: Ahs9cC6PMGhasB5zUboUVNBJxAStmX1aeENDiWLz2AXH
          config-prefix: state
          other-prefix:
            - bnusd_authority
        - name: asset_manager
          program-id: 5G7Q2xM5qU4UWd3z4CW9YSEiVnfZmTUS1mbhSSZwTEJQ
          config-prefix: state
          other-prefix:
            - vault_native
      cp-nids:
        - 0x2.icon
      alt-address: 4BFCep44Zdbvoo4tmnUwQgjU5gdk8fXeEfshYP85A14n
      nid: solana-test
      home-dir: /home/relayer/.centralized-relay
      start-tx-sign:
      tx-confirmation-time: 1s

  sui:
    type: sui
    value:
      rpc-url: https://rpc.ankr.com/sui_testnet
      address: 0x675b6d9e32904ecc705fc17201111f3637b5dcb69f8be35d3ce49a7161de6548
      nid: sui-test
      xcall-package-id: 0xff60814fac7930b9890fc6582efa0e02e72956584d18adef77d23ed4643325bd
      xcall-storage-id: 0x60add4475c91742470074396ba29b6d62572abd1ac08c18abe228be949c21420
      connection-module: cluster_entry
      connection-id: cluster-1
      connection-cap-id: 0x68f3d6261631c7a83159d84017dbf3a984b0e137853f0f5cb62e101ebb042ca3
      dapps:
        - package-id: 0x273507b0283232d745a8cef8c4ebb794708dc4522d00d93464daefa44345a5e1
          constants:
            clock: "0x6"
          modules:
            - name: xcall_manager
              cap-id: 0xafa02d4592affcb14285a5dfd585ef5b47ad7ad68b4bbdcb659342915f8dd982
              config-id: 0x1b8071a73e61a4b60e026875061311e9f9146d89ceb1120c35519f8e4dc47b2f
            - name: asset_manager
              cap-id: 0x0d7e657ed9e5494dccd2abcfec849d471bc43716a03a7b48b78bdc906b55535d
              config-id: 0x323451f3f9526a54469f3d1db25d384dc5d9d20b63ad0db0bb42d62e0a0bf154
            - name: balanced_dollar_crosschain
              cap-id: 0xb3ffbef01bb8d5067ee36f2ddafac049ae62b7d4f70c349c9bb579b9a271e942
              config-id: 0x1ecad1dfd5c22849414ba2f68113cc182a93ff01d9901c4800d0168ffd6e0cf5
      gas-limit: 5000000
      disabled: false
      start-tx-digest:
      poll-interval: 6s
