global:
  timeout: 10s
  kms-key-id: 5ef77041-d1e6-4af1-9a41-e49a4b45efb6
chains:
  icon:
    type: icon
    value:
      rpc-url: https://lisbon.net.solidwallet.io/api/v3/
      start-height: 0
      address: hxcd808d9a16234ef3419d19b422dfe61d3a93aeb2
      contracts:
        connection: cx81520d8d497651f2c050c4a10aaf51176f37230d
        xcall: cx15a339fa60bd86225050b22ea8cd4a9d7cd8bb83
      finality-block: 0
      nid: 0x2.icon
      disabled: false
      step-min: 1
      step-limit: 100000000000
      step-adjustment: 50
  stellar:
    type: stellar
    value:
      disabled: false
      nid: 0x2.stellar
      soroban-url: https://soroban-testnet.stellar.org/
      horizon-url: https://horizon-testnet.stellar.org/
      address: GA77PVPU6CB32XVGFP2BKFSHKG4HUWWF2IKLB6FOFFSWOS4VHEIKSOT6
      contracts:
        connection: CDN5AZB2CXBHDD6J5U26DKCOPKS5EALPY6WMKEN4L2CWNJFPU4DTWFKT
        # xcall: CBIBOMZJUAXJUHW2UKPUVJ6PBUA372VCECB2HYUOJOYGZD34VSKG7LTD
      max-inclusion-fee: 100000
      block-interval: 5s
      network-passphrase: Test SDF Network ; September 2015
      start-height: 0