version: "3.8"

services:
  kms:
    container_name: crly-kms
    image: nsmithuk/local-kms
    volumes:
      - ./kms/data:/data
      - ./kms/init:/init
    ports:
      - 4799:8080

  rly0:
    container_name: rly0
    image: centralized-relay:latest
    volumes:
      - ./.aws:/home/relayer/.aws
      - ./wallets:/home/relayer/wallets
      - ./data/rly0/data:/home/relayer/.centralized-relay/data
      - ./data/rly0/keystore:/home/relayer/.centralized-relay/keystore
      - ./rly0-config.yaml:/home/relayer/.centralized-relay/config.yaml
      - ./rly0-entrypoint.sh:/home/relayer/.centralized-relay/entrypoint.sh

    environment:
      - AWS_ENDPOINT_URL=http://kms:8080
    depends_on:
      - kms
    entrypoint: /home/relayer/.centralized-relay/entrypoint.sh

  rly1:
    container_name: rly1
    image: centralized-relay:latest
    volumes:
      - ./.aws:/home/relayer/.aws
      - ./wallets:/home/relayer/wallets
      - ./data/rly1/data:/home/relayer/.centralized-relay/data
      - ./data/rly1/keystore:/home/relayer/.centralized-relay/keystore
      - ./rly1-config.yaml:/home/relayer/.centralized-relay/config.yaml
      - ./rly1-entrypoint.sh:/home/relayer/.centralized-relay/entrypoint.sh

    environment:
      - AWS_ENDPOINT_URL=http://kms:8080
    depends_on:
      - kms
    entrypoint: /home/relayer/.centralized-relay/entrypoint.sh