global:
    timeout: 10s
    kms-key-id: 5ef77041-d1e6-4af1-9a41-e49a4b45efb6
chains:
    icon:
        type: icon
        value:
            rpc-url: https://lisbon.net.solidwallet.io/api/v3/
            start-height: 0
            address: hxd9967431c2b3dc39e4275460280eaa050a834c0d
            contracts:
                connection: cx6664f06c1e19dc1d8fcbd031e99e9d623a411136
                xcall: cx15a339fa60bd86225050b22ea8cd4a9d7cd8bb83
            finality-block: 0
            nid: 0x2.icon
            disabled: false
            step-min: 1
            step-limit: 100000000000
            step-adjustment: 50
    solana:
        type: solana
        value:
            disabled: false
            rpc-url: https://rpc.ankr.com/solana_devnet/98af665db4f1c6be2ed8ce7d8caed10aade053c5bd7880844d8806b0eada8317
            address: 7Fn9wQNv7E3UKJsdytMSQSKbpu8GVwRfBGDhr2ZYdAme
            xcall-program: CnZLCetiXFr963LgQpPKhkQu7N9z64b4eKcBp28Wps4J
            connection-program: 6XavVgM7dk9YH6DgkuPNP9XRRNcQ9oQdKHRHQMg8LXsM
            other-connections: []
            dapps:
                - name: xcall_manager
                  program-id: D8E4MdQH6p3vfiX23Kq5x4xM1v4aUfhp3sM2HYGinvzk
                - name: balanced_dollar
                  program-id: 9cmYrvKr6JxkQfkTM5Nuf1LTGSGPRH4x3VczCa6GqjkE
                - name: asset_manager
                  program-id: Gk5un55A5ExrMvx7rp4HvygNik2trCrM325rTDBGGSbb
            cp-nids:
                - 0x2.icon
            alt-address: 6RV74u7xgbGD7Dg9zyHsMejtZYc6aY5e7CbBkWYJJuHT
            nid: solana
            home-dir: /home/relayer/.centralized-relay
            start-tx-sign: 3kyGHNwhaUTt21zxPCZ2pbcU137DKFb6YeEKn9V3Rpw1TuhWrX8hrhd8gCErzkieU1pnGY9EcuVmFuLG3k8yzHvz
