global:
  timeout: 10s
  kms-key-id: 5ef77041-d1e6-4af1-9a41-e49a4b45efb6
chains:
  icon:
    type: icon
    value:
      rpc-url: https://lisbon.net.solidwallet.io/api/v3/
      start-height: 0
      address: hxd9967431c2b3dc39e4275460280eaa050a834c0d
      contracts:
        connection: cxcfdc270edd2a1f10036fa12a2ab1da4fb1262963
        xcall: cx15a339fa60bd86225050b22ea8cd4a9d7cd8bb83
      finality-block: 0
      nid: 0x2.icon
      disabled: false
      step-min: 1
      step-limit: 100000000000
      step-adjustment: 50
  solana:
    type: solana
    value:
      disabled: false
      rpc-url: https://rpc.ankr.com/solana_devnet
      address: 7GoW5ACKgsKcjWKnfPXeGyZHMSNBJkqHFwjt5ex2i73z
      xcall-program: BknkMw3sonNXVTW2mzuhKEJmmt4PSVei1HbQiDuWVny4
      connection-program: Hch96XZHaSEqaX5LBiMQ9dXVJXCSexJFpMMX5s6mS7ad
      other-connections:
        - 9AQweV7eGvXAq4M2UAGYmTds7vN73LH453jUwXA5Uv4q
      dapps:
        - name: xcall_manager
          program-id: 4eAQxDi6UJokDysb9YMrXNJNcRChotpYory5M5ReD16i
          config-prefix: state
        - name: balanced_dollar
          program-id: Ahs9cC6PMGhasB5zUboUVNBJxAStmX1aeENDiWLz2AXH
          config-prefix: state
          other-prefix:
            - bnusd_authority
        - name: asset_manager
          program-id: 5G7Q2xM5qU4UWd3z4CW9YSEiVnfZmTUS1mbhSSZwTEJQ
          config-prefix: state
          other-prefix:
            - vault_native
      cp-nids:
        - 0x2.icon
      alt-address: 9zdvWRLFU19dMr6ScTDGwRuUcZBUyZgVPKvoRCgZzrqf
      nid: solana-test
      home-dir: /home/relayer/.centralized-relay
      start-tx-sign:
      tx-confirmation-time: 1s
