global:
    timeout: 10s
    kms-key-id: 5ef77041-d1e6-4af1-9a41-e49a4b45efb6
chains:
    icon:
        type: icon
        value:
            rpc-url: https://lisbon.net.solidwallet.io/api/v3/
            start-height: 0
            address: hxd9967431c2b3dc39e4275460280eaa050a834c0d
            contracts:
                connection: cx70c607227cd4ee4681f4400b2fc1c2f67e48cba5
                xcall: cx15a339fa60bd86225050b22ea8cd4a9d7cd8bb83
            finality-block: 0
            nid: 0x2.icon
            disabled: false
            step-min: 1
            step-limit: 100000000000
            step-adjustment: 50
    solana:
        type: solana
        value:
            disabled: false
            rpc-url: https://api.testnet.solana.com/
            address: 7GoW5ACKgsKcjWKnfPXeGyZHMSNBJkqHFwjt5ex2i73z
            xcall-program: D2Y1zv93GygWbo5simDx9J7E9g2g2sAEqckex5BRidrp
            connection-program: 8o1Eu3ishe9DPB8bedjbRewGEhDEZHurXHA9TSpeudQ6
            other-connections:
            dapps:
                - name: mock_dapp
                  program-id: D5LgccEsHB8A8KCxYe8NbR225bB8nR6HogfirAM9pJ4D
                  config-prefix: config
                # - name: xcall_manager
                #   program-id: AKgQ6MECUga4rUWRwiDkj3XZetp7eTrAhArdPBF7W3qJ
                #   config-prefix: state
                # - name: balanced_dollar
                #   program-id: DnTw1FNEm3TAGXPMJSpNWau1TukRCtxMW9GUzM3eJxYN
                #   config-prefix: state
                #   other-prefix:
                #     - bnusd_authority
                # - name: asset_manager
                #   program-id: BGzeVEn4LkKp8U7dhBP9SnUdYXsdkmFVjrG7awamyqWZ
                #   config-prefix: state
                #   other-prefix:
                #     - vault_native
            cp-nids:
                - 0x2.icon
            alt-address: EenoGQ1cN3H6MdELt5UaZ4UcFLBvbGw1vRmii2kCXjFo
            nid: solana
            home-dir: /home/relayer/.centralized-relay
            start-tx-sign: 
