global:
    timeout: 10s
    kms-key-id: 5ef77041-d1e6-4af1-9a41-e49a4b45efb6
chains:
    icon:
        type: icon
        value:
            rpc-url: https://lisbon.net.solidwallet.io/api/v3/
            start-height: 0
            address: hxd9967431c2b3dc39e4275460280eaa050a834c0d
            contracts:
                connection: cxcfdc270edd2a1f10036fa12a2ab1da4fb1262963
                xcall: cx15a339fa60bd86225050b22ea8cd4a9d7cd8bb83
            finality-block: 0
            nid: 0x2.icon
            disabled: false
            step-min: 1
            step-limit: 100000000000
            step-adjustment: 50
    solana:
        type: solana
        value:
            disabled: false
            rpc-url: https://api.devnet.solana.com/
            address: 7GoW5ACKgsKcjWKnfPXeGyZHMSNBJkqHFwjt5ex2i73z
            xcall-program: DCCrvzYbxFbFz3K76T2RZji9PJgbuLMaKd62AS9hRwvJ
            connection-program: GEjcGQPrD469divUhLZB4BeEcD81ZbcbrC9nLULCv8Dt
            other-connections:
            dapps:
                - name: mock_dapp
                  program-id: 7s8YcrV7Yz52titGNq1hfRYpFmau8H81KZEuvZLbdVLj
                  config-prefix: config
                - name: xcall_manager
                  program-id: AKgQ6MECUga4rUWRwiDkj3XZetp7eTrAhArdPBF7W3qJ
                  config-prefix: state
                - name: balanced_dollar
                  program-id: DnTw1FNEm3TAGXPMJSpNWau1TukRCtxMW9GUzM3eJxYN
                  config-prefix: state
                  other-prefix:
                    - bnusd_authority
                - name: asset_manager
                  program-id: BGzeVEn4LkKp8U7dhBP9SnUdYXsdkmFVjrG7awamyqWZ
                  config-prefix: state
                  other-prefix:
                    - vault_native
            cp-nids:
                - 0x2.icon
            alt-address: 
            nid: solana-test
            home-dir: /home/relayer/.centralized-relay
            start-tx-sign: 
