global:
    timeout: 10s
    kms-key-id: 5ef77041-d1e6-4af1-9a41-e49a4b45efb6
chains:
    icon:
        type: icon
        value:
            rpc-url: https://lisbon.net.solidwallet.io/api/v3/
            start-height: 0
            address: hxd9967431c2b3dc39e4275460280eaa050a834c0d
            contracts:
                connection: cxcfdc270edd2a1f10036fa12a2ab1da4fb1262963
                xcall: cx15a339fa60bd86225050b22ea8cd4a9d7cd8bb83
            finality-block: 0
            nid: 0x2.icon
            disabled: false
            step-min: 1
            step-limit: 100000000000
            step-adjustment: 50
    solana:
        type: solana
        value:
            disabled: false
            rpc-url: https://api.testnet.solana.com/
            address: 7GoW5ACKgsKcjWKnfPXeGyZHMSNBJkqHFwjt5ex2i73z
            xcall-program: DCCrvzYbxFbFz3K76T2RZji9PJgbuLMaKd62AS9hRwvJ
            connection-program: A3A496cjPkB9jYhKAj3ET84XUmTbxTU1F6CnahftPLob
            other-connections:
                - 7iLXLLbvUx7oLcNHCZxF8oAQ6gwyawHM3a1JHMKk5SoW
            dapps:
                - name: xcall_manager
                  program-id: 7WCY7VifxPQ35LbGB8fespWDqXdHJ9oEHWZLCKhe8cyc
                  config-prefix: state
                - name: balanced_dollar
                  program-id: 41uJ59VqLXWJVDDiU6PHPn8Mzz5KtJGTDS6ZA2cLCdbe
                  config-prefix: state
                  other-prefix:
                    - bnusd_authority
                - name: asset_manager
                  program-id: 7LCni1XXMkBmjpW5S88k63wbdyPvRkjY18fjN2hSKoCF
                  config-prefix: state
                  other-prefix:
                    - vault_native
            cp-nids:
                - 0x2.icon
            alt-address: EenoGQ1cN3H6MdELt5UaZ4UcFLBvbGw1vRmii2kCXjFo
            nid: solana-test
            home-dir: /home/relayer/.centralized-relay
            start-tx-sign: 
