global:
  timeout: ""
  kms-key-id: 9b7c08a8-465f-459f-a132-a31d9cb7a87b
  cluster-mode:
    enabled: true
    key: 044b39d213d473d8f1b87e5bcc91919eec9c3038bcca707467fa0db6ccb667192f7b70e81bb696ad2e36205dc09c4dd275ee58f118bbd128aab512aa462fde1e98
chains:
  archway:
    type: cosmos
    value:
      rpc-url: https://rpc-1.archway.nodes.guru
      start-height: 0
      address: ""
      contracts:
        connection: archway1lvmx2u6f47n8yr0dg7fangur2l72nwxxklasqyal2fhtpyw9uxfqmudel8
      finality-block: 0
      nid: archway-1
      decimals: 18
      disabled: true
      cluster-mode: true
      grpc-url: grpc.mainnet.archway.io:443
      keyring-backend: memory
      keyring-dir: /data/archway
      account-prefix: archway
      denomination: aarch
      gas-prices: 900000000000aarch
      gas-adjustment: 1.5
      min-gas-amount: 20000
      max-gas-amount: 4000000
      tx-confirmation-interval: 5s
      broadcast-mode: sync
      sign-mode: SIGN_MODE_DIRECT
      simulate: true
      extra-codecs: ""
      block-batch-size: 50
  bsc:
    type: evm
    value:
      rpc-url: https://rpc.ankr.com/bsc/98af665db4f1c6be2ed8ce7d8caed10aade053c5bd7880844d8806b0eada8317
      start-height: 0
      address:
      contracts:
        connection: 0x20b056e975EEB8Ad4552FAD829F7990dE45d23D5
      finality-block: 60
      nid: 0x38.bsc
      decimals: 18
      disabled: true
      cluster-mode: true
      websocket-url: wss://rpc.ankr.com/bsc/ws/98af665db4f1c6be2ed8ce7d8caed10aade053c5bd7880844d8806b0eada8317
      gas-min: 0
      gas-limit: 30000000
      gas-adjustment: 200
      block-batch-size: 50
  icon:
    type: icon
    value:
      rpc-url: https://ctz.solidwallet.io/api/v3/
      start-height: 0
      address: hx8603b060c3bcd86fbc0a9973cd0685cf69d9ea8c
      contracts:
        aggregation: cxb2f67b60ef68f8f239d247e1f23412c0685d4b9b
      finality-block: 0
      nid: 0x1.icon
      decimals: 18
      disabled: false
      cluster-mode: true
      step-min: 0
      step-limit: 5000000
      step-adjustment: 50
  # avalanche:
  #   type: evm
  #   value:
  #     rpc-url: https://rpc.ankr.com/avalanche/98af665db4f1c6be2ed8ce7d8caed10aade053c5bd7880844d8806b0eada8317
  #     start-height: 0
  #     address: ""
  #     contracts:
  #       connection: 0x133E6B7e7E10cD3Fc68eF84EdD9622b3e39C3812
  #     finality-block: 60
  #     nid: 0xa86a.avax
  #     decimals: 18
  #     disabled: true
  #     cluster-mode: true
  #     websocket-url: wss://rpc.ankr.com/avalanche/ws/98af665db4f1c6be2ed8ce7d8caed10aade053c5bd7880844d8806b0eada8317
  #     gas-min: 0
  #     gas-limit: 30000000
  #     gas-adjustment: 200
  #     block-batch-size: 50
  # base:
  #   type: evm
  #   value:
  #     rpc-url: https://base-mainnet.g.alchemy.com/v2/4pUcbG5h_DRfuSbGY9O585RK_yrJusHM
  #     start-height: 0
  #     address: ""
  #     contracts:
  #       connection: 0x133E6B7e7E10cD3Fc68eF84EdD9622b3e39C3812
  #     finality-block: 60
  #     nid: 0x2105.base
  #     decimals: 18
  #     disabled: true
  #     cluster-mode: true
  #     websocket-url: wss://base-mainnet.g.alchemy.com/v2/4pUcbG5h_DRfuSbGY9O585RK_yrJusHM
  #     gas-min: 0
  #     gas-limit: 100056000
  #     gas-adjustment: 50
  #     block-batch-size: 50

  # injective:
  #   type: cosmos
  #   value:
  #     rpc-url: https://injective-rpc.publicnode.com:443
  #     start-height: 0
  #     address: ""
  #     contracts:
  #       connection: ""
  #     finality-block: 0
  #     nid: injective-1
  #     decimals: 18
  #     disabled: true
  #     cluster-mode: true
  #     grpc-url: injective-grpc.publicnode.com:443
  #     keyring-backend: memory
  #     keyring-dir: /data/injective
  #     account-prefix: inj
  #     denomination: inj
  #     gas-prices: 20000inj
  #     gas-adjustment: 1.5
  #     min-gas-amount: 1
  #     max-gas-amount: 3360000
  #     tx-confirmation-interval: 1s
  #     broadcast-mode: sync
  #     sign-mode: SIGN_MODE_DIRECT
  #     simulate: true
  #     extra-codecs: injective
  #     block-batch-size: 50
