global:
  timeout: 10s
  kms-key-id: 5ef77041-d1e6-4af1-9a41-e49a4b45efb6
chains:
  icon:
    type: icon
    value:
      rpc-url: https://lisbon.net.solidwallet.io/api/v3/
      start-height: 0
      address: hxd9967431c2b3dc39e4275460280eaa050a834c0d
      contracts:
        connection: cxcfdc270edd2a1f10036fa12a2ab1da4fb1262963
        xcall: cx15a339fa60bd86225050b22ea8cd4a9d7cd8bb83
      finality-block: 0
      nid: 0x2.icon
      disabled: false
      step-min: 1
      step-limit: 100000000000
      step-adjustment: 50
  stellar:
    type: stellar
    value:
      disabled: false
      nid: 0x2.stellar
      soroban-url: https://soroban-testnet.stellar.org/
      horizon-url: https://horizon-testnet.stellar.org/
      address: GCQ5YPTO5ORNZ7WMADFAWP2D7NOJBZGDLWAUYNMSNLIHRNMSJXXFFWE3
      contracts:
        connection: CCPY4SCOKJ5C4EMEC2ZETGIBINRX6YP6KCWDWGWIAYARKE5LWWPQG7E3
        xcall: CBTZ4JG6KDZMP462WYXE23TPDIFT276ZV6B55TAHR3MQSR5H7VHU7VS5
      max-inclusion-fee: 100000
      block-interval: 5s
      network-passphrase: Test SDF Network ; September 2015
      start-height: 0