#!/bin/bash

# testnet
SOROBAN_URL=https://soroban-testnet.stellar.org/
NETWORK_PASSPHRASE="Test SDF Network ; September 2015"
RELAYER_ADDR=GCQ5YPTO5ORNZ7WMADFAWP2D7NOJBZGDLWAUYNMSNLIHRNMSJXXFFWE3
RELAYER_ACC=relayer

# mainnet
SOROBAN_URL=
HORIZON_URL=