global:
  timeout: 10s
  kms-key-id: 5ef77041-d1e6-4af1-9a41-e49a4b45efb6
  # cluster-mode:
  #   enabled: true
  #   key: 046bc928ee4932efd619ec4c00e0591e932cf2cfef13a59f6027da1c6cba36b35d91238b54aece19825025a9c7cb0bc58a60d5c49e7fc8e5b39fcc4c2193f5feb2
chains:
  avalanche:
    type: evm
    value:
      rpc-url: https://api.avax-test.network/ext/bc/C/rpc
      start-height: 0
      address: 0x2e73d181EC82796E9CEB77950e9488441ABaFa04
      contracts:
        connection: 0x0789F14b511292DE6A5b63304f41854e4d188Bd6
        xcall: 0x28ecb198e86a7FcA1cf51032635967fc26cDDAaD
      finality-block: 10
      nid: 0xa869.fuji
      decimals: 18
      disabled: false
      cluster-mode: true
      websocket-url: wss://ws-nd-507-756-317.p2pify.com/b01d81c64a3b7454f7a40a20ef44a1ce/ext/bc/C/ws
      gas-min: 0
      gas-limit: 100056000
      gas-adjustment: 50
      block-batch-size: 50
  icon:
    type: icon
    value:
      rpc-url: https://lisbon.net.solidwallet.io/api/v3/
      start-height: 0
      address: hx71d3f2e4d7973bd6b8e818fa0174f81b064d6548
      contracts:
        aggregation: cx89b8b5c95c4ff38e83ed15374caf854dca0c51d4
        connection: cxdccc9298c4cfd0b505c50b6ec1bc111bd442d080
        xcall: cx15a339fa60bd86225050b22ea8cd4a9d7cd8bb83
      finality-block: 0
      nid: 0x2.icon
      decimals: 18
      disabled: false
      cluster-mode: true
      step-min: 1
      step-limit: 100000000000
      step-adjustment: 50
  archway:
    type: cosmos
    value:
      rpc-url: https://rpc.constantine.archway.io:443
      start-height: 0
      address: archway1fmfsejk7d6xeg5n63c5ljwaup02tv54c55263h
      contracts:
        connection: archway1dq3g9k26dcnzxyp236t0nan7nt9jp82hzdjc43naxchkuz6g9z6s8x33f4
        xcall: archway1h04c8eqr99dnsw6wqx80juj2vtuxth70eh65cf6pnj4zan6ms4jqshc5wk
      finality-block: 0
      nid: archway
      decimals: 18
      disabled: false
      grpc-url: grpc.constantine.archway.io:443
      keyring-backend: memory
      keyring-dir: /Users/sherpalden/.centralized-relay/archway
      account-prefix: archway
      denomination: aconst
      gas-prices: 900000000000aconst
      gas-adjustment: 1.5
      min-gas-amount: 20000
      max-gas-amount: 4000000
      tx-confirmation-interval: 5s
      broadcast-mode: sync
      sign-mode: SIGN_MODE_DIRECT
      simulate: true
      extra-codecs: ""
      block-batch-size: 50
